targets:
  $default:
    builders:
      freezed:
        options:
          # Generate copyWith, ==, toString, etc.
          union_value_case: pascal
      json_serializable:
        options:
          # Generate explicit toJson/fromJson methods
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
